-- BookMyShow initial schema (V1).
-- Matches the entities under com.umang.bookmyshow.model.entity.
-- Flyway applies this on startup; Hibernate is set to validate-only against it.

CREATE TABLE cities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    state       VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone         VARCHAR(32),
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE movies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    duration_minutes INT,
    genre            VARCHAR(128),
    language         VARCHAR(128),
    release_date     DATE,
    rating           VARCHAR(16),
    poster_url       VARCHAR(1024),
    trailer_url      VARCHAR(1024),
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);

CREATE TABLE theaters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    city_id       BIGINT REFERENCES cities (id),
    address       VARCHAR(1024),
    latitude      NUMERIC(10, 6),
    longitude     NUMERIC(10, 6),
    total_screens INT,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE screens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id  BIGINT REFERENCES theaters (id),
    name        VARCHAR(255),
    total_seats INT,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT REFERENCES screens (id),
    row_num     VARCHAR(8),
    seat_number INT,
    seat_type   VARCHAR(16),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE shows (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id        BIGINT REFERENCES movies (id),
    screen_id       BIGINT REFERENCES screens (id),
    show_date       DATE,
    show_time       TIME,
    end_time        TIME,
    base_price      NUMERIC(10, 2),
    available_seats INT,
    total_seats     INT,
    status          VARCHAR(16),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE show_seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    BIGINT REFERENCES shows (id),
    seat_id    BIGINT REFERENCES seats (id),
    price      NUMERIC(10, 2),
    status     VARCHAR(16),
    locked_at  TIMESTAMPTZ,
    locked_by  BIGINT REFERENCES users (id),
    booking_id BIGINT,
    version    BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT REFERENCES users (id),
    show_id           BIGINT REFERENCES shows (id),
    booking_reference VARCHAR(64) NOT NULL UNIQUE,
    total_amount      NUMERIC(10, 2),
    booking_status    VARCHAR(16),
    payment_status    VARCHAR(16),
    payment_id        VARCHAR(64),
    payment_method    VARCHAR(32),
    booked_at         TIMESTAMPTZ,
    expires_at        TIMESTAMPTZ,
    confirmed_at      TIMESTAMPTZ,
    cancelled_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE booking_seats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   BIGINT REFERENCES bookings (id),
    show_seat_id BIGINT REFERENCES show_seats (id),
    price        NUMERIC(10, 2),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE payments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id             BIGINT REFERENCES bookings (id),
    amount                 NUMERIC(10, 2),
    payment_method         VARCHAR(32),
    payment_gateway        VARCHAR(64),
    gateway_transaction_id VARCHAR(128),
    status                 VARCHAR(16),
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL
);

-- Indexes for the hot read/lookup paths.
CREATE INDEX idx_shows_movie_date ON shows (movie_id, show_date);
CREATE INDEX idx_show_seats_show_status ON show_seats (show_id, status);
CREATE INDEX idx_bookings_user ON bookings (user_id);
CREATE INDEX idx_bookings_status_expiry ON bookings (booking_status, expires_at);
CREATE INDEX idx_theaters_city ON theaters (city_id);
