CREATE TABLE idempotency_keys (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key        VARCHAR(255) NOT NULL UNIQUE,
    booking_id             BIGINT,
    payment_id             BIGINT,
    gateway_transaction_id VARCHAR(128),
    payment_status         VARCHAR(16),
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL
);
