-- Transactional outbox: booking events are written here in the same tx as the state
-- change, then relayed to Kafka by OutboxPoller. Replaces the old publish-after-commit
-- dual-write.

CREATE TABLE outbox_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    payload      TEXT         NOT NULL,
    published    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL,
    published_at TIMESTAMPTZ
);

-- The poller scans for unpublished rows oldest-first; a partial index keeps that cheap
-- as published rows accumulate.
CREATE INDEX idx_outbox_unpublished ON outbox_events (created_at)
    WHERE published = FALSE;
